apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  selector:
    matchLabels:
      app: order-management
  replicas: 2

  # Because it crashed during pods creation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: thisuraka/order-management-application:{{tag}}
          ports:
            - containerPort: 8081
