apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-management
  name: order-management
spec:
  ports:
    - protocol: TCP
      port: 8081
  selector:
    app: order-management
  type: LoadBalancer
